# Generated by Django 5.0.2 on 2024-02-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clients_alter_product_about_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='comment',
            field=models.TextField(blank=True, default='...'),
        ),
    ]
